### ISSUE TITLE
Build fails with compset  2000_SATM_XLND_SICE_SOCN_XROF_XGLC_SWAV 

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/CMEPS#13]
This compset is used in scripts_regression_tests.py 
test_f_createnewcase_with_user_compset (__main__.J_TestCreateNewcase) ... FAIL
```
FAIL: test_f_createnewcase_with_user_compset (__main__.J_TestCreateNewcase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./scripts_regression_tests.py", line 542, in test_f_createnewcase_with_user_compset
    run_cmd_assert_result(self, "./case.build", from_dir=testdir)
  File "./scripts_regression_tests.py", line 69, in run_cmd_assert_result
    test_obj.assertEqual(stat, expected_stat, msg=msg)
AssertionError: 
COMMAND: ./case.build
FROM_DIR: /glade/scratch/jedwards/scripts_regression_test.20190604_145832/TestCreateNewcase/testcreatenewcase_with_user_compset
SHOULD HAVE WORKED, INSTEAD GOT STAT 1
OUTPUT: Building case in directory /gpfs/fs1/scratch/jedwards/scripts_regression_test.20190604_145832/TestCreateNewcase/testcreatenewcase_with_user_compset
sharedlib_only is False
model_only is False
Setting resource.RLIMIT_STACK to -1 from (-1, -1)
Generating component namelists as part of build
Creating component namelists
  2019-06-04 14:58:38 atm
   Calling /gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/components/stub_comps/satm/cime_config/buildnml
  2019-06-04 14:58:38 lnd
   Calling /gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/components/xcpl_comps/xlnd/cime_config/buildnml
  2019-06-04 14:58:38 ice
   Calling /gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/components/stub_comps/sice/cime_config/buildnml
  2019-06-04 14:58:38 ocn
   Calling /gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/components/stub_comps/socn/cime_config/buildnml
  2019-06-04 14:58:38 rof
   Calling /gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/components/xcpl_comps/xrof/cime_config/buildnml
  2019-06-04 14:58:38 glc
   Calling /gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/components/xcpl_comps/xglc/cime_config/buildnml
  2019-06-04 14:58:38 wav
   Calling /gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/components/stub_comps/swav/cime_config/buildnml
  2019-06-04 14:58:38 esp
   Calling /gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/components/stub_comps/sesp/cime_config/buildnml
  2019-06-04 14:58:38 cpl
   Calling /gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/drivers/nuopc/cime_config/buildnml
Writing nuopc_runseq will skip components ['ATM', 'ICE', 'OCN', 'WAV', 'ESP']
ERRPUT: Traceback (most recent call last):
  File "./case.build", line 147, in <module>
    _main_func(__doc__)
  File "./case.build", line 142, in _main_func
    save_build_provenance=save_build_provenance)
  File "/gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 550, in case_build
    return run_and_log_case_status(functor, "case.build", caseroot=caseroot)
  File "/gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 1702, in run_and_log_case_status
    rv = func()
  File "/gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 549, in <lambda>
    save_build_provenance)
  File "/gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 490, in _case_build_impl
    complist, ninst_build, smp_value, model_only, buildlist)
  File "/gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/scripts/Tools/../../scripts/lib/CIME/build.py", line 222, in _build_checks
    case.create_namelists()
  File "/gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/scripts/Tools/../../scripts/lib/CIME/case/preview_namelists.py", line 87, in create_namelists
    run_sub_or_cmd(cmd, (caseroot), "buildnml", (self, caseroot, compname), case=self)
  File "/gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/scripts/Tools/../../scripts/lib/CIME/utils.py", line 382, in run_sub_or_cmd
    getattr(mod, subname)(*subargs)
  File "/gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/drivers/nuopc/cime_config/buildnml", line 467, in buildnml
    _create_drv_namelists(case, infile, confdir, nmlgen, files)
  File "/gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/drivers/nuopc/cime_config/buildnml", line 241, in _create_drv_namelists
    _create_runseq(case, coupling_times)
  File "/gpfs/fs1/work/jedwards/sandboxes/UFSCOMP/cime/src/drivers/nuopc/cime_config/buildnml", line 341, in _create_runseq
    runseq(case, coupling_times)
UnboundLocalError: local variable 'runseq' referenced before assignment


----------------------------------------------------------------------
```

**Comment by mvertens** [comment]
Fixed.
